name: dart_grid
description: Dart Grid type data implementation
version: 1.0.0
repository: https://gitlab.com/dipdev.studio/open-source/dart-grid

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
